locations:
  waiting-lobby:
    ==: org.bukkit.Location
    world: world
    x: 165.5
    y: 135.0
    z: 76.5
    yaw: 0.0
    pitch: 0.0
  minigames:
    runaway:
      ==: org.bukkit.Location
      world: world
      x: 165.5
      y: 135.0
      z: 76.5
      yaw: 0.0
      pitch: 0.0
    math:
      ==: org.bukkit.Location
      world: world
      x: 165.5
      y: 135.0
      z: 76.5
      yaw: 0.0
      pitch: 0.0