name: BedlessTournament
version: '1.0-SNAPSHOT'
main: info.mester.network.partygames.PartyGames
api-version: '1.21'
bootstrapper: info.mester.network.partygames.Bootstrap
loader: info.mester.network.partygames.Loader
load: STARTUP
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: true
      join-classpath: true
authors:
  - Mester
description: The paper plugin for the Bedless Tournament
website: https://github.com/MesterMan03/blntournament
contributors:
  - Pansexuality (lol)
  - Lots of coffee
  - Sleepless nights
  - Send help please