name: PartyGamesCore
version: '1.0'
main: info.mester.network.partygames.api.PartyGamesCore
api-version: '1.21'
bootstrapper: info.mester.network.partygames.api.Bootstrapper
load: STARTUP
authors:
  - Mester
description: Core API for Party Games
website: https://github.com/MesterNetwork/PartyGames
contributors:
  - ChatGPT
  - Methamphetamine